- name: restart a particular instance by its ID
  hosts: localhost
  tasks:
    - ec2_instance:
        region: ap-south-1
        state: stopped
        filters:
          instance-state-name: running
