- name: restart a particular instance by its ID
  hosts: localhost
  tasks:
    - ec2_instance:
        aws_access_key: AKIAYZ4ROK5JX6A4YH2K
        aws_secret_key: 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
        region: ap-south-1
        state: stopped
        filters:
          instance-state-name: running
