- name: EC2 instance termination
  hosts: localhost
  tasks:
    - ec2_instance:
        aws_access_key: AKIAYZ4ROK5JX6A4YH2K
        aws_secret_key: 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
        region: ap-south-1
        instance_ids: i-08d74887425a86c99
        state: absent
